compareCompile:
- 'echo "Hello World"'
- ''
compareRun:
- 'echo "Hello World"'
- ''
compiling:
  Sql:
  - 'echo "Hello World"'
  - ''
judgingCompile:
- <<!Python:BIN_FILE>>
- -m py_compile "<<Std_Judge>>"
judgingRun:
- <<!Python:BIN_FILE>>
- '"<<Std_Judge>>"'
running:
  Sql:
  - 'echo "Hello World"'
  - ''
